version: '3.8'

name: saas-starter-db

services:
  postgres:
    image: postgres:16-alpine
    container_name: saas-starter-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_db
    volumes:
      - saas_starter_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - saas-starter-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: saas-starter-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    volumes:
      - saas_starter_pgadmin_data:/var/lib/pgadmin
    networks:
      - saas-starter-network

networks:
  saas-starter-network:
    name: saas-starter-network
    driver: bridge

volumes:
  saas_starter_postgres_data:
    name: saas-starter-postgres-data
  saas_starter_pgadmin_data:
    name: saas-starter-pgadmin-data 